server:
   port: 8080
   servlet:
      context-path: /api
spring:
   datasource:
      first:
         jdbc-url: jdbc:mysql://192.168.44.128:3306/tsdb?useSSL=false&allowPublicKeyRetrieval=true
         username: root
         password: root
         driver-class-name: com.mysql.cj.jdbc.Driver
      second:
         jdbc-url: jdbc:mysql://192.168.44.128:3306/tsdb2?useSSL=false&allowPublicKeyRetrieval=true
         username: root
         password: root
         driver-class-name: com.mysql.cj.jdbc.Driver
   jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
   servlet:
      multipart:
         enabled: true
         max-file-size: 10MB
         max-request-size: 100MB
   rabbitmq:
      host: 192.168.44.128
      port: 5672
      username: admin
      password: admin
   redis:
      database: 0
      cluster:
         nodes:
            - 192.168.44.128:7001
            - 192.168.44.128:7002
            - 192.168.44.128:7003
            - 192.168.44.128:7004
            - 192.168.44.128:7005
            - 192.168.44.128:7006
    lettuce: null
#password: 123456
      pool: null
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
mybatis:
   mapper-locations: classpath:mapper/*.xml
   type-aliases-package: com.example.demo.model
   configuration:
      map-underscore-to-camel-case: true
task:
   print: 0 0/1 * * * ?
netty:
   port: 7000
   url: 172.18.73.135
logging:
   level:
      com:
         example:
            #showSql
            demo: debug
biz:
   user:
      topic: item_queue
component:
   mq: true
   redis: true
   mysql: true

elasticsearch:
   ip: 192.168.44.128:9200
author:
   name: dev